export interface Place {
  id: number;
  place: string;
  country: string;
  image: string;
}

export const placesData: Place[] = [
  {
    id: 1,
    place: "Paris",
    country: "France",
    image: "/placeholder.svg?height=400&width=400&text=Paris",
  },
  {
    id: 2,
    place: "Rome",
    country: "Italy",
    image: "/placeholder.svg?height=300&width=300&text=Rome",
  },
  {
    id: 3,
    place: "Barcelona",
    country: "Spain",
    image: "/placeholder.svg?height=300&width=600&text=Barcelona",
  },
  {
    id: 4,
    place: "Tokyo",
    country: "Japan",
    image: "/placeholder.svg?height=600&width=300&text=Tokyo",
  },
  {
    id: 5,
    place: "New York",
    country: "USA",
    image: "/placeholder.svg?height=300&width=300&text=New+York",
  },
  {
    id: 6,
    place: "London",
    country: "UK",
    image: "/placeholder.svg?height=300&width=600&text=London",
  },
  {
    id: 7,
    place: "Sydney",
    country: "Australia",
    image: "/placeholder.svg?height=300&width=300&text=Sydney",
  },
  {
    id: 8,
    place: "Cairo",
    country: "Egypt",
    image: "/placeholder.svg?height=600&width=300&text=Cairo",
  },
  {
    id: 9,
    place: "Rio de Janeiro",
    country: "Brazil",
    image: "/placeholder.svg?height=400&width=400&text=Rio",
  },
  {
    id: 10,
    place: "Cape Town",
    country: "South Africa",
    image: "/placeholder.svg?height=300&width=300&text=Cape+Town",
  },
  {
    id: 11,
    place: "Amsterdam",
    country: "Netherlands",
    image: "/placeholder.svg?height=300&width=300&text=Amsterdam",
  },
  {
    id: 12,
    place: "Dubai",
    country: "UAE",
    image: "/placeholder.svg?height=300&width=600&text=Dubai",
  },
  {
    id: 13,
    place: "Singapore",
    country: "Singapore",
    image: "/placeholder.svg?height=600&width=300&text=Singapore",
  },
  {
    id: 14,
    place: "Bangkok",
    country: "Thailand",
    image: "/placeholder.svg?height=300&width=300&text=Bangkok",
  },
  {
    id: 15,
    place: "Istanbul",
    country: "Turkey",
    image: "/placeholder.svg?height=300&width=300&text=Istanbul",
  },
  {
    id: 16,
    place: "Marrakech",
    country: "Morocco",
    image: "/placeholder.svg?height=300&width=600&text=Marrakech",
  },
  {
    id: 17,
    place: "Venice",
    country: "Italy",
    image: "/placeholder.svg?height=400&width=400&text=Venice",
  },
  {
    id: 18,
    place: "Prague",
    country: "Czech Republic",
    image: "/placeholder.svg?height=300&width=300&text=Prague",
  },
  {
    id: 19,
    place: "Kyoto",
    country: "Japan",
    image: "/placeholder.svg?height=600&width=300&text=Kyoto",
  },
  {
    id: 20,
    place: "Santorini",
    country: "Greece",
    image: "/placeholder.svg?height=300&width=300&text=Santorini",
  },
  {
    id: 21,
    place: "Bali",
    country: "Indonesia",
    image: "/placeholder.svg?height=300&width=600&text=Bali",
  },
  {
    id: 22,
    place: "Machu Picchu",
    country: "Peru",
    image: "/placeholder.svg?height=300&width=300&text=Machu+Picchu",
  },
  {
    id: 23,
    place: "Petra",
    country: "Jordan",
    image: "/placeholder.svg?height=600&width=300&text=Petra",
  },
  {
    id: 24,
    place: "Reykjavik",
    country: "Iceland",
    image: "/placeholder.svg?height=400&width=400&text=Reykjavik",
  },
  {
    id: 25,
    place: "Vienna",
    country: "Austria",
    image: "/placeholder.svg?height=300&width=300&text=Vienna",
  },
  {
    id: 26,
    place: "Budapest",
    country: "Hungary",
    image: "/placeholder.svg?height=300&width=300&text=Budapest",
  },
  {
    id: 27,
    place: "Seoul",
    country: "South Korea",
    image: "/placeholder.svg?height=300&width=600&text=Seoul",
  },
  {
    id: 28,
    place: "Havana",
    country: "Cuba",
    image: "/placeholder.svg?height=600&width=300&text=Havana",
  },
  {
    id: 29,
    place: "Florence",
    country: "Italy",
    image: "/placeholder.svg?height=300&width=300&text=Florence",
  },
  {
    id: 30,
    place: "Dubrovnik",
    country: "Croatia",
    image: "/placeholder.svg?height=300&width=300&text=Dubrovnik",
  },
  {
    id: 31,
    place: "Queenstown",
    country: "New Zealand",
    image: "/placeholder.svg?height=300&width=600&text=Queenstown",
  },
  {
    id: 32,
    place: "Lisbon",
    country: "Portugal",
    image: "/placeholder.svg?height=400&width=400&text=Lisbon",
  },
  {
    id: 33,
    place: "San Francisco",
    country: "USA",
    image: "/placeholder.svg?height=300&width=300&text=San+Francisco",
  },
  {
    id: 34,
    place: "Berlin",
    country: "Germany",
    image: "/placeholder.svg?height=600&width=300&text=Berlin",
  },
  {
    id: 35,
    place: "Stockholm",
    country: "Sweden",
    image: "/placeholder.svg?height=300&width=300&text=Stockholm",
  },
  {
    id: 36,
    place: "Hong Kong",
    country: "China",
    image: "/placeholder.svg?height=300&width=300&text=Hong+Kong",
  },
  {
    id: 37,
    place: "Vancouver",
    country: "Canada",
    image: "/placeholder.svg?height=300&width=600&text=Vancouver",
  },
  {
    id: 38,
    place: "Buenos Aires",
    country: "Argentina",
    image: "/placeholder.svg?height=600&width=300&text=Buenos+Aires",
  },
  {
    id: 39,
    place: "Chiang Mai",
    country: "Thailand",
    image: "/placeholder.svg?height=300&width=300&text=Chiang+Mai",
  },
  {
    id: 40,
    place: "Seville",
    country: "Spain",
    image: "/placeholder.svg?height=400&width=400&text=Seville",
  },
  {
    id: 41,
    place: "Jaipur",
    country: "India",
    image: "/placeholder.svg?height=300&width=300&text=Jaipur",
  },
  {
    id: 42,
    place: "Cusco",
    country: "Peru",
    image: "/placeholder.svg?height=300&width=300&text=Cusco",
  },
  {
    id: 43,
    place: "Bruges",
    country: "Belgium",
    image: "/placeholder.svg?height=300&width=600&text=Bruges",
  },
  {
    id: 44,
    place: "Zanzibar",
    country: "Tanzania",
    image: "/placeholder.svg?height=600&width=300&text=Zanzibar",
  },
  {
    id: 45,
    place: "Kyiv",
    country: "Ukraine",
    image: "/placeholder.svg?height=300&width=300&text=Kyiv",
  },
  {
    id: 46,
    place: "Cartagena",
    country: "Colombia",
    image: "/placeholder.svg?height=300&width=300&text=Cartagena",
  },
  {
    id: 47,
    place: "Salzburg",
    country: "Austria",
    image: "/placeholder.svg?height=300&width=600&text=Salzburg",
  },
  {
    id: 48,
    place: "Luang Prabang",
    country: "Laos",
    image: "/placeholder.svg?height=400&width=400&text=Luang+Prabang",
  },
  {
    id: 49,
    place: "Krakow",
    country: "Poland",
    image: "/placeholder.svg?height=300&width=300&text=Krakow",
  },
  {
    id: 50,
    place: "Hoi An",
    country: "Vietnam",
    image: "/placeholder.svg?height=600&width=300&text=Hoi+An",
  },
  // { id: 51, place: "Amalfi Coast", country: "Italy", image: "/placeholder.svg?height=300&width=300&text=Amalfi+Coast" },
  // { id: 52, place: "Serengeti", country: "Tanzania", image: "/placeholder.svg?height=300&width=300&text=Serengeti" },
  // { id: 53, place: "Maldives", country: "Maldives", image: "/placeholder.svg?height=300&width=600&text=Maldives" },
  // { id: 54, place: "Sedona", country: "USA", image: "/placeholder.svg?height=600&width=300&text=Sedona" },
  // { id: 55, place: "Cinque Terre", country: "Italy", image: "/placeholder.svg?height=300&width=300&text=Cinque+Terre" },
  // { id: 56, place: "Angkor Wat", country: "Cambodia", image: "/placeholder.svg?height=400&width=400&text=Angkor+Wat" },
  // { id: 57, place: "Galápagos", country: "Ecuador", image: "/placeholder.svg?height=300&width=300&text=Galapagos" },
  // { id: 58, place: "Zurich", country: "Switzerland", image: "/placeholder.svg?height=300&width=300&text=Zurich" },
  // { id: 59, place: "Cappadocia", country: "Turkey", image: "/placeholder.svg?height=300&width=600&text=Cappadocia" },
  // { id: 60, place: "Fiji", country: "Fiji", image: "/placeholder.svg?height=600&width=300&text=Fiji" },
  // { id: 61, place: "Maui", country: "USA", image: "/placeholder.svg?height=300&width=300&text=Maui" },
  // {
  //   id: 62,
  //   place: "Patagonia",
  //   country: "Argentina/Chile",
  //   image: "/placeholder.svg?height=300&width=300&text=Patagonia",
  // },
  // { id: 63, place: "Banff", country: "Canada", image: "/placeholder.svg?height=300&width=600&text=Banff" },
  // { id: 64, place: "Bagan", country: "Myanmar", image: "/placeholder.svg?height=400&width=400&text=Bagan" },
  // { id: 65, place: "Tulum", country: "Mexico", image: "/placeholder.svg?height=300&width=300&text=Tulum" },
  // { id: 66, place: "Hallstatt", country: "Austria", image: "/placeholder.svg?height=600&width=300&text=Hallstatt" },
  // { id: 67, place: "Chefchaouen", country: "Morocco", image: "/placeholder.svg?height=300&width=300&text=Chefchaouen" },
  // { id: 68, place: "Zermatt", country: "Switzerland", image: "/placeholder.svg?height=300&width=300&text=Zermatt" },
  // {
  //   id: 69,
  //   place: "Bora Bora",
  //   country: "French Polynesia",
  //   image: "/placeholder.svg?height=300&width=600&text=Bora+Bora",
  // },
  // { id: 70, place: "Mostar", country: "Bosnia", image: "/placeholder.svg?height=600&width=300&text=Mostar" },
  // { id: 71, place: "Varanasi", country: "India", image: "/placeholder.svg?height=300&width=300&text=Varanasi" },
  // {
  //   id: 72,
  //   place: "Atacama Desert",
  //   country: "Chile",
  //   image: "/placeholder.svg?height=400&width=400&text=Atacama+Desert",
  // },
  // { id: 73, place: "Oia", country: "Greece", image: "/placeholder.svg?height=300&width=300&text=Oia" },
  // { id: 74, place: "Guilin", country: "China", image: "/placeholder.svg?height=300&width=300&text=Guilin" },
  // {
  //   id: 75,
  //   place: "Plitvice Lakes",
  //   country: "Croatia",
  //   image: "/placeholder.svg?height=300&width=600&text=Plitvice+Lakes",
  // },
  // {
  //   id: 76,
  //   place: "Antelope Canyon",
  //   country: "USA",
  //   image: "/placeholder.svg?height=600&width=300&text=Antelope+Canyon",
  // },
  // { id: 77, place: "Positano", country: "Italy", image: "/placeholder.svg?height=300&width=300&text=Positano" },
  // {
  //   id: 78,
  //   place: "Salar de Uyuni",
  //   country: "Bolivia",
  //   image: "/placeholder.svg?height=300&width=300&text=Salar+de+Uyuni",
  // },
  // {
  //   id: 79,
  //   place: "Lofoten Islands",
  //   country: "Norway",
  //   image: "/placeholder.svg?height=300&width=600&text=Lofoten+Islands",
  // },
  // { id: 80, place: "Meteora", country: "Greece", image: "/placeholder.svg?height=400&width=400&text=Meteora" },
  // { id: 81, place: "Zhangjiajie", country: "China", image: "/placeholder.svg?height=300&width=300&text=Zhangjiajie" },
  // { id: 82, place: "Halong Bay", country: "Vietnam", image: "/placeholder.svg?height=600&width=300&text=Halong+Bay" },
  // {
  //   id: 83,
  //   place: "Cliffs of Moher",
  //   country: "Ireland",
  //   image: "/placeholder.svg?height=300&width=300&text=Cliffs+of+Moher",
  // },
  // { id: 84, place: "Sossusvlei", country: "Namibia", image: "/placeholder.svg?height=300&width=300&text=Sossusvlei" },
  // {
  //   id: 85,
  //   place: "Milford Sound",
  //   country: "New Zealand",
  //   image: "/placeholder.svg?height=300&width=600&text=Milford+Sound",
  // },
  // {
  //   id: 86,
  //   place: "Faroe Islands",
  //   country: "Denmark",
  //   image: "/placeholder.svg?height=600&width=300&text=Faroe+Islands",
  // },
  // { id: 87, place: "Ubud", country: "Indonesia", image: "/placeholder.svg?height=300&width=300&text=Ubud" },
  // { id: 88, place: "Siem Reap", country: "Cambodia", image: "/placeholder.svg?height=400&width=400&text=Siem+Reap" },
  // { id: 89, place: "Edinburgh", country: "Scotland", image: "/placeholder.svg?height=300&width=300&text=Edinburgh" },
  // { id: 90, place: "Giza", country: "Egypt", image: "/placeholder.svg?height=300&width=300&text=Giza" },
  // { id: 91, place: "Whistler", country: "Canada", image: "/placeholder.svg?height=300&width=600&text=Whistler" },
  // { id: 92, place: "Socotra", country: "Yemen", image: "/placeholder.svg?height=600&width=300&text=Socotra" },
  // {
  //   id: 93,
  //   place: "Lauterbrunnen",
  //   country: "Switzerland",
  //   image: "/placeholder.svg?height=300&width=300&text=Lauterbrunnen",
  // },
  // { id: 94, place: "Raja Ampat", country: "Indonesia", image: "/placeholder.svg?height=300&width=300&text=Raja+Ampat" },
  // {
  //   id: 95,
  //   place: "Torres del Paine",
  //   country: "Chile",
  //   image: "/placeholder.svg?height=300&width=600&text=Torres+del+Paine",
  // },
  // { id: 96, place: "Kamchatka", country: "Russia", image: "/placeholder.svg?height=400&width=400&text=Kamchatka" },
  // {
  //   id: 97,
  //   place: "Faial Island",
  //   country: "Portugal",
  //   image: "/placeholder.svg?height=300&width=300&text=Faial+Island",
  // },
  // {
  //   id: 98,
  //   place: "Socotra Island",
  //   country: "Yemen",
  //   image: "/placeholder.svg?height=600&width=300&text=Socotra+Island",
  // },
  // {
  //   id: 99,
  //   place: "Kamchatka Peninsula",
  //   country: "Russia",
  //   image: "/placeholder.svg?height=300&width=300&text=Kamchatka+Peninsula",
  // },
  // {
  //   id: 100,
  //   place: "Madagascar",
  //   country: "Madagascar",
  //   image: "/placeholder.svg?height=300&width=300&text=Madagascar",
  // },
];
